### ISSUE TITLE
harmonization-like style transfer with out-of-domain style references

### ISSUE THREAD

**Issue by Riad123321** [curryjung/DiffStyle_official#3]
Hi great paper
working with out of domain images are not clear actually in this research paper you said that using   out of domain  image as content is not good but your result was really good how did you do that???

did you took h content from another layer and combine it with h style from the middle but their sizes are different or there is another way??

i tried to make out of domain image as style image but when adding the noise to move it to T time step it will lose all of it's info and our diffusion model will not be able to generate it again and it's style will not appear on the generated image at the end .my diffusion model work  fine just if we know the noise that we used to generate X content and the noise that we used to generate X style but we don't have that noise for out of domain images

 
thanks

**Comment by curryjung** [comment]
Thank you for your attention to our work.

1) In our paper, we clearly said that using out-of-domain images as content is not good.  out-of-domain images are only used as styles. 

2) We did not include experiments taking contents from another layer rather than h-space. However, we found that using out-of-domain images as content also does not work using another layer as content holder.

3) In order to get style components out of images, one should apply DDIM inversion without stochasticity. Simply adding random noise will not preserve the style of even in-domain images. To ensure the possibility of using desired out-of-domain images as style, we commend checking out the reconstruction of the images before contact injection.


Thanks

**Comment by Riad123321** [comment]
thank for your replay 
so we can say that we can make our ddpm model able to reconstruct the style image even if it is out of domain by using ddim sampling process but as i know even will ddim we should start with XT which is random noise in our case it is our style image in time step T after that the  reconstruction process will be determnistic in other words we need to make the noise the we will something that will create the style image image  correct me if iam wrong

**Comment by Riad123321** [comment]
> Thank you for your attention to our work.
> 
> 1. In our paper, we clearly said that using out-of-domain images as content is not good.  Out-of-domain images are only used as styles.
> 2. We did not include experiments taking contents from another layer rather than h-space. However, we found that using out-of-domain images as content also does not work using another layer as content holder.
> 3. In order to get style components out of images, one should apply DDIM inversion without stochasticity. Simply adding random noise will not preserve the style of even in-domain images. To ensure the possibility of using desired out-of-domain images as style, we commend checking out the reconstruction of the images before contact injection.
> 
> Thanks



> thank for your reply
> so we can say that we can make our ddpm model able to reconstruct the style image even if it is out of domain by using ddim sampling process but as i know even with ddim we should start with XT which is random noise in our case it is our style image in time step T after that the reconstruction process will be determnistic in other words we need to make the noise the we will use something that will create the style image correct me if iam wrong

thank for your reply
so we can say that we can make our ddpm model able to reconstruct the style image even if it is out of domain by using ddim sampling process but as i know even with ddim we should start with XT which is random noise in our case it is our style image in time step T after that the reconstruction process will be determnistic in other words we need to make the noise the we will use something that will create the style image correct me if iam wrong
