### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by aisagarw** [curryjung/DiffStyle_official#4]
Hi, 
I have been trying to generate results (diff_style) using the test images available for afhq dog dataset.. I downloaded the afhqdog_pt2 checkpoint from the [provided link](https://onedrive.live.com/?authkey=%21AOIJGI8FUQXvFf8&id=72419B431C262344%21103807&cid=72419B431C262344). Attaching the results I am getting for these test images for the diffstyle case. I wanted to understand what could be the possible reasons for this. Maybe I am missing out on setting certain hyperparameters? Would appreciate any help in fixing the issue. Thanks in advance!

![image](https://github.com/curryjung/DiffStyle_official/assets/44503856/8004ad05-eda2-455e-b94d-dd20a5ead5cf)

**Comment by curryjung** [comment]
I'm not sure but I guess that excessive gamma value could be the reason. The best hyperparameter can be different depending on what pretrained model is in use.

**Comment by aisagarw** [comment]
Can you please tell me which variable in your code refers to gamma? I can see only **_sch_gamma_**

**Comment by curryjung** [comment]
I meant "hs_coeff"!

Probably 0.3~0.4 would be the best.

Thanks

**Comment by aisagarw** [comment]
Thanks! That helped in improving the results. 
Another doubt I have is - which argument in **main.py** refers to **t_boost**?

**Comment by curryjung** [comment]
Sorry for the confusion.

't_boost' is 't_noise' in main.py!

**Comment by aisagarw** [comment]
sure, thanks!
